# Generated by Django 4.1.1 on 2022-09-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MoveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('move_name', models.CharField(max_length=200)),
                ('dmg', models.IntegerField()),
                ('stun', models.IntegerField()),
                ('guard', models.CharField(max_length=10)),
                ('startup', models.IntegerField()),
                ('guard_advantage', models.IntegerField()),
                ('invul', models.CharField(max_length=200)),
                ('special_props', models.CharField(max_length=500)),
            ],
        ),
    ]
