# Generated by Django 4.1.1 on 2022-09-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelist',
            name='invul',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movelist',
            name='special_props',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
