# Generated by Django 4.1.1 on 2022-09-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movelist_character_movelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
