# Generated by Django 4.1.1 on 2022-09-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_movelist_character_movelist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movelist',
            old_name='special_props',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='movelist',
            name='invul',
        ),
    ]
