# Generated by Django 4.1.1 on 2022-09-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_movelist_dmg_remove_movelist_guard_advantage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndyMoveListTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='comment')),
            ],
        ),
    ]
