# Generated by Django 4.1.1 on 2022-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_andymovelisttransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelist',
            name='guard_adv',
            field=models.CharField(max_length=5, null=True, verbose_name='guard advantage'),
        ),
    ]
