# Generated by Django 4.1.1 on 2022-09-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_movelist_guard_adv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movelist',
            name='guard',
        ),
    ]
