# Generated by Django 4.1.1 on 2022-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_movelist_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelist',
            name='startup',
            field=models.CharField(max_length=5, verbose_name='startup'),
        ),
    ]
