# Generated by Django 4.1.1 on 2022-09-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_movelist_startup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AndyMoveListTransfer',
        ),
        migrations.RemoveField(
            model_name='movelist',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='movelist',
            name='img',
        ),
    ]
