# Generated by Django 4.1.1 on 2022-09-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_andymovelisttransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelist',
            name='character_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_list', to='api.character'),
        ),
        migrations.AddField(
            model_name='movelist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
