# Generated by Django 4.1.1 on 2022-09-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_movelist_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelist',
            name='stun',
            field=models.IntegerField(default=None, null=True, verbose_name='stun'),
        ),
    ]
