# Generated by Django 4.1.1 on 2022-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_movelist_guard_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelist',
            name='damage',
            field=models.CharField(max_length=10, null=True, verbose_name='damage'),
        ),
    ]
