# Generated by Django 4.1.1 on 2022-09-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_movelist_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelist',
            name='stun',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='stun'),
        ),
    ]
