# Generated by Django 4.1.1 on 2022-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_movelist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movelist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
