# Generated by Django 4.1.1 on 2022-09-20 18:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_character_thumbnail_alter_movelist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=api.models.upload_to),
        ),
    ]
